cms/urls.py
"""
Definición de rutas URL para la aplicación.

Esta lista de patrones de URL define las rutas accesibles en la aplicación,
incluyendo vistas de administración, autenticación, perfiles y restablecimiento de contraseñas.

Rutas:
    - 'admin/': Ruta para acceder al panel de administración de Django.
    - '': Ruta para la página de inicio, que utiliza la vista `home_view`.

    Autenticación (Auth):
    - 'register/': Ruta para el registro de usuarios, utilizando `register_view`.
    - 'login/': Ruta para el inicio de sesión de usuarios, utilizando `login_view`.
    - 'logout/': Ruta para cerrar la sesión de usuarios, utilizando `logout_view`.
    - 'password-reset/': Ruta para solicitar el restablecimiento de la contraseña, utilizando `reset_password_view`.
    - 'reset/<uidb64>/<token>/': Ruta para confirmar el restablecimiento de la contraseña, utilizando `password_reset_confirm_view`.

    Comentadas:
    - Las rutas comentadas corresponden a vistas de restablecimiento de contraseña basadas en clases de Django, 
    que pueden reemplazar a las vistas personalizadas si se desean utilizar las vistas predeterminadas de Django.

    Perfil (Profile):
    - 'profile/': Ruta para la vista del perfil del usuario autenticado, utilizando `profile_view`.
    - 'profile/<int:id>/': Ruta para la vista de perfil de otro usuario, utilizando `other_profile_view`.
    - 'change-password/': Ruta para cambiar la contraseña del usuario autenticado, utilizando `change_password`.
"""
from content.views import kanban_board, report_post, update_content_state, view_version, validate_permission_kanban_api, \
    like_content, dislike_content, view_count_share
from django.contrib import admin
from django.urls import include, path
from app.auth.views import register_view, login_view, logout_view, reset_password_view, password_reset_confirm_view
from app.profile.views import other_profile_view, profile_view, change_password
from app.views import *
from content.views import ContentCreateView, ContentUpdateView, view_content
from ckeditor_uploader import views
from django.conf import settings
from django.conf.urls.static import static
from category.views import categories_by_type
from rating import views as rating_views
from stadistic.views import view_stadistics, top_liked, top_rating, top_disliked, top_view, top_shares
from suscription.views import suscribe_category, unsuscribe_category, create_checkout_session, stripe_webhook, \
    my_subscriptions, finances, category_totals, category_timeline, daily_totals, table_data, export_to_excel

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', home_view, name='home'),

    #Auth
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('password-reset/', reset_password_view, name='password_reset'),
    path('reset/<uidb64>/<token>/', password_reset_confirm_view, name='password_reset_confirm'),

    # Profile
    path('profile/', profile_view, name='profile'),
    path('profile/<int:id>/', other_profile_view, name='profile_view'),
    path('change-password/', change_password, name='change_password'),

    # Content - Edit (Autor - Editor)
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("content-upload/", views.upload, name="content_ckeditor_upload"),
    path('content/new/', ContentCreateView.as_view(), name='content-create'),
    path('content/<int:pk>/edit/', ContentUpdateView.as_view(), name='content-update'),
    path('content/<int:id>/', view_content, name='content_view'),
    path('content/<int:content_id>/history/<int:history_id>', view_version, name='view_content_version'),
    path('tablero/', kanban_board, name='kanban_board'),
    path('api/update-content-state/<int:content_id>/', update_content_state, name='update_content_state'),
    path('content/<int:pk>/edit/', ContentUpdateView.as_view(), name='edit_content'),
    path('report/<int:content_id>/', report_post, name='report_post'),  # Ruta para reportar
    path('api/validate-permission-kanban/', validate_permission_kanban_api, name='validate_permission_kanban_api'),

    # Content - Reactions
    path('like/<int:content_id>/', like_content, name='like_content'),
    path('dislike/<int:content_id>/', dislike_content, name='dislike_content'),

    # Rating
    path('rate/<int:content_id>/', rating_views.rate_content, name='rate_content'),

    # Share
    path('share/<int:content_id>/', view_count_share, name='share_content'),

    # Category
    path('category/<str:type>/', categories_by_type, name='categories_by_type'),
    # Category suscription
    path('category/<int:category_id>/suscribe/', suscribe_category, name='suscribe_category'),
    path('category/<int:category_id>/unsuscribe/', unsuscribe_category, name='unsuscribe_category'),
    path('create-checkout-session/<int:category_id>/', create_checkout_session, name='create_checkout_session'),
    path('webhook/stripe/', stripe_webhook, name='stripe_webhook'),
    path('subscriptions/', my_subscriptions, name='subscriptions'),

    #Stadistics
    path('stadistics/', view_stadistics, name='view_stadistics'),
    path('stadistics/likes/', top_liked, name='top_liked'),
    path('stadistics/dislikes/', top_disliked, name='top_disliked'),
    path('stadistics/rating/', top_rating, name='top_rating'),
    path('stadistics/views/', top_view, name='top_view'),
    path('stadistics/shares/', top_shares, name='top_shares'),

    path('finances/',finances, name='finances'),
    path('finances/category_totals/',category_totals, name='finances_category'),
    path('finances/category_timeline/', category_timeline, name='finances_category_timeline'),
    path('finances/daily_totals/', daily_totals, name='finances_daily_totals'),
    path('finances/table_data/', table_data, name='finances_table_data'),
    path('finances/export_to_excel/', export_to_excel, name='finances_export_to_excel'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.core.exceptions import ValidationError
from simple_history.models import HistoricalRecords
from app.models import CustomUser
from category.models import Category
from taggit.managers import TaggableManager
from django.contrib.auth import get_user_model
from django.db.models import Avg

class Content (models.Model):
    """
    Modelo que representa un contenido en la base de datos.

    Define las propiedades y comportamientos asociados a los contenidos creados en la plataforma,
    como su título, estado, categoría, autor, estadísticas y validaciones.

    :attribute title: Título del contenido.
    :type title: CharField
    :attribute summary: Resumen del contenido.
    :type summary: TextField
    :attribute category: Relación con el modelo `Category`.
    :type category: ForeignKey
    :attribute autor: Relación con el modelo `CustomUser`.
    :type autor: ForeignKey
    :attribute is_active: Indica si el contenido está activo.
    :type is_active: BooleanField
    :attribute date_create: Fecha de creación del contenido.
    :type date_create: DateTimeField
    :attribute date_expire: Fecha de expiración del contenido.
    :type date_expire: DateTimeField
    :attribute date_published: Fecha de publicación del contenido.
    :type date_published: DateTimeField
    :attribute content: Texto enriquecido con CKEditor para el contenido principal.
    :type content: RichTextUploadingField
    :attribute tags: Administrador de etiquetas para asociar palabras clave al contenido.
    :type tags: TaggableManager
    :attribute likes: Relación con los usuarios que han dado "me gusta" al contenido.
    :type likes: ManyToManyField
    :attribute dislikes: Relación con los usuarios que han dado "no me gusta" al contenido.
    :type dislikes: ManyToManyField
    :attribute rating_avg: Promedio de calificaciones del contenido.
    :type rating_avg: FloatField
    :attribute likes_count: Cantidad total de "me gusta".
    :type likes_count: IntegerField
    :attribute dislikes_count: Cantidad total de "no me gusta".
    :type dislikes_count: IntegerField
    :attribute views_count: Número total de visualizaciones.
    :type views_count: IntegerField
    :attribute shares_count: Número total de veces que el contenido fue compartido.
    :type shares_count: IntegerField
    :attribute important: Indica si el contenido está marcado como "destacado".
    :type important: BooleanField
    """

    title = models.CharField(max_length=255, verbose_name='Título')
    summary = models.TextField(max_length=255, verbose_name='Resumen')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categoría')
    autor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Autor')
    is_active = models.BooleanField(default=True, verbose_name='Activo')
    date_create= models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    date_expire = models.DateTimeField(null=True, blank=True, verbose_name='Fecha de expiración')
    date_published = models.DateTimeField(null=True, blank=True, verbose_name='Fecha de publicación')
    content = RichTextUploadingField(verbose_name='Contenido')  # Campo de texto enriquecido con CKEditor 5
    tags = TaggableManager()
    history = HistoricalRecords(excluded_fields=['rating_avg', 'likes_count', 'dislikes_count', 'views_count', 'shares_count', 'important'])
    likes = models.ManyToManyField(get_user_model(), related_name='liked_content', blank=True)
    dislikes = models.ManyToManyField(get_user_model(), related_name='disliked_content', blank=True)
    rating_avg = models.FloatField(default = 0.0, verbose_name="Promedio de calificación")
    likes_count = models.IntegerField(default=0, verbose_name="Cantidad de likes")
    dislikes_count = models.IntegerField(default=0, verbose_name="Cantidad de dislikes")
    views_count = models.IntegerField(default=0, verbose_name="Cantidad de visualizaciones")
    shares_count = models.IntegerField(default=0, verbose_name="Cantidad de compartidos")
    important = models.BooleanField(default=False, verbose_name="Destacado")

    class StateChoices(models.TextChoices):
        """
        Enumeración de estados posibles para un contenido.

        Define las opciones disponibles para el campo `state` del contenido, asegurando que solo se utilicen
        valores predefinidos.

        :attribute draft: Contenido en estado de borrador.
        :type draft: str
        :attribute revision: Contenido en estado de revisión.
        :type revision: str
        :attribute to_publish: Contenido en estado "a publicar".
        :type to_publish: str
        :attribute publish: Contenido publicado.
        :type publish: str
        :attribute inactive: Contenido inactivo.
        :type inactive: str
        """

        draft = 'draft', ('Borrador')
        revision = 'revision', ('Revisión')
        to_publish = 'to_publish', ('A publicar')
        publish = 'publish', ('Publicado')
        inactive = 'inactive', ('Inactivo')

    state = models.CharField(
        choices=StateChoices.choices,
        default=StateChoices.draft,
        max_length=20,
        verbose_name=('Estado')
    )

    def clean(self):
        """
        Valida que el estado del contenido sea uno de los definidos en `StateChoices`.

        :raises ValidationError: Si el estado no pertenece a las opciones válidas.
        """

        # Validar que el estado sea uno de los definidos en StateChoices
        if self.state not in dict(Content.StateChoices.choices):
            raise ValidationError(f"Estado '{self.state}' no es válido.")

    def save(self, *args, **kwargs):
        """
        Sobrescribe el metodo `save` para incluir validaciones personalizadas antes de guardar.

        :param args: Argumentos posicionales adicionales.
        :type args: list
        :param kwargs: Argumentos nombrados adicionales.
        :type kwargs: dict
        """
        self.clean()  # Llama a la validación personalizada
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Contenido'
        verbose_name_plural = 'Contenidos'
        db_table = 'content'


    def __str__(self):
        """
        Devuelve una representación en cadena del contenido.

        :return: El título del contenido.
        :rtype: str
        """
        return f"{self.title}"


    def update_rating_avg(self):
        """
        Actualiza el promedio de calificación del contenido.

        Calcula el promedio de las calificaciones asociadas al contenido y actualiza el campo `rating_avg`.
        """

        avg_rating = self.rating_set.aggregate(Avg('rating'))['rating__avg']
        self.rating_avg = avg_rating or 0.0
        self.save()

    def get_state_name(self, state):
        """
        Devuelve el nombre descriptivo del estado del contenido en español.

        :param state: Estado del contenido (uno de los valores definidos en `StateChoices`).
        :type state: str
        :return: Nombre descriptivo del estado en español.
        :rtype: str
        """
        if state == Content.StateChoices.draft:
            return "Borrador"
        elif state == Content.StateChoices.publish:
            return "Publicado"
        elif state == Content.StateChoices.inactive:
            return "Inactivo"
        elif state == Content.StateChoices.to_publish:
            return "A publicar"
        elif state == Content.StateChoices.revision:
            return "Revision"
        else:
            return "Desconocido"
        

class Report(models.Model):
    """
    Modelo que representa un reporte asociado a un contenido.

    Captura los detalles sobre un reporte realizado por un usuario o visitante,
    incluyendo el motivo y una descripción.

    :attribute content: Contenido reportado.
    :type content: ForeignKey
    :attribute reported_by: Usuario que realizó el reporte. Es opcional.
    :type reported_by: ForeignKey
    :attribute email: Correo electrónico del reportante.
    :type email: EmailField
    :attribute name: Nombre del reportante.
    :type name: CharField
    :attribute reason: Motivo del reporte.
    :type reason: CharField
    :attribute description: Descripción del motivo del reporte.
    :type description: TextField
    :attribute created_at: Fecha de creación del reporte.
    :type created_at: DateTimeField
    """

    REASON_CHOICES = [
        ('spam', 'Spam'),
        ('inappropriate', 'Contenido inapropiado'),
        ('abuse', 'Abuso o acoso'),
        ('other', 'Otro'),
    ]

    content = models.ForeignKey(Content, on_delete=models.CASCADE,verbose_name=('Contenido'))
    reported_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True,verbose_name=('Reportado por'))  # Para que el campo sea opcional
    email = models.EmailField(verbose_name=('Correo Electrónico'))
    name = models.CharField(max_length=255, verbose_name=('Nombre'))
    reason = models.CharField(max_length=50, choices=REASON_CHOICES,verbose_name=('Motivo'))
    description = models.TextField(verbose_name=('Descripción'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=('Fecha de creación'))

    def __str__(self):
        """
        Devuelve una representación legible del reporte.

        :return: Una cadena que describe el reporte, indicando el reportante y el contenido.
        :rtype: str
        """
        return f"Reporte de {self.email if self.email else self.reported_by} sobre {self.content.title}"

templates/content/content_form.html
{% extends "base.html" %}
{% load static i18n %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'ckeditor/ckeditor/contents.css' %}" rel="stylesheet">
</head>

{% block content %}

{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success' %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <i class="bi bi-check-circle me-1"></i>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif message.tags == 'error' %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="bi bi-exclamation-octagon me-1"></i>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif message.tags == 'warning' %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <i class="bi bi-exclamation-triangle me-1"></i>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}
<div class="pagetitle">
  <h1>
    {% if object %}
      Editar contenido
    {% else %}
      Crear contenido
    {% endif %}
  </h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Inicio</a></li>
      <!-- <li class="breadcrumb-item">Anterior</li> -->
      <li class="breadcrumb-item active">
        {% if object %}
          Editar contenido
        {% else %}
          Crear contenido
        {% endif %}
      </li>
    </ol>
  </nav>
</div><!-- End Page Title -->
<section class="section">
  <div class="row">
    <div class="col-lg-12">

      <div class="card">
        <div class="card-body">
          <form method="post" class="my-4" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="button" onclick="history.back()"class="btn btn-secondary">
                <i class="bi bi-x-circle me-1"></i>
                Cancelar
              </button>
              <button name="action" value="save" class="btn btn-success">
                <i class="bi bi-save me-1"></i>
                Guardar
              </button>
              {% if content.id  %}
              <a type="button" target="_blank" class="btn btn-info" href="/content/{{ content.id }}">
                <i class="bi bi-eye me-1"></i>
                Visualizar
              </a>
              {% endif %}
          </form>

        </div>
      </div>

    </div>

  </div>
</section>
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script>
CKEDITOR.replace('{{ form.content.name }}', {
        extraPlugins: 'uploadimage',
        filebrowserUploadUrl: '{% url "content_ckeditor_upload" %}',
        toolbar: 'full',
        height: 300,
        width: '100%'
      });
</script>
{% endblock content %}

templates/content/report_form_partial.html
<form id="reportForm" method="post" action="{% url 'report_post' content_id=post.id %}">
    {% csrf_token %}
    {% if user.is_authenticated %}
      <!-- Ocultamos los labels y campos cuando el usuario está autenticado -->
      <div class="d-none">
        <p>
          <label for="id_nombre">Nombre:</label>
          {{ form.name }}
        </p>
        <p>
          <label for="id_email">Email:</label>
          {{ form.email }}
        </p>
      </div>
    {% else %}
      <!-- Mostramos los labels y campos si el usuario no está autenticado -->
      <p>
        <label for="id_nombre">Nombre:</label>
        {{ form.name }}
      </p>
      <p>
        <label for="id_email">Email:</label>
        {{ form.email }}
      </p>
    {% endif %}
    
    <!-- Campos comunes que siempre se muestran -->
    <p>
      <label for="id_reason">Motivo del reporte:</label>
      {{ form.reason }}
    </p>
    <p>
      <label for="id_description">Descripción:</label>
      {{ form.description }}
    </p>


</form>

templates/content/view_version.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}

{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success' %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <i class="bi bi-check-circle me-1"></i>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif message.tags == 'error' %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="bi bi-exclamation-octagon me-1"></i>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif message.tags == 'warning' %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <i class="bi bi-exclamation-triangle me-1"></i>
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}
<div class="pagetitle">
  <h1>Version de contenido</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Inicio</a></li>
      <li class="breadcrumb-item"><a href="/content/{{ content.id }}">Contenido</a></li>
      <li class="breadcrumb-item active">Version de contenido</li>
    </ol>
  </nav>
</div><!-- End Page Title -->
<section class="section">
  <div class="row">
    <div class="col-lg-12">

      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-4 text-start">
              {{ history.history_date|default:"" }}
            </div>
            <div class="col-4 text-center">
                Editado por:
              <a href="/profile/{{ history.history_user_id }}">{{ history.history_user.name }}</a>
            </div>
            <div class="col-4 text-end">
              {{ history.category.name }}
            </div>
          </div>
        </div>
        <div class="card-body">
          <h1 class="text-center mt-4 fw-bold">{{ history.title }}</h1>
          <h4> {{history.summary}} </h4>
          <section>
            {{ history.content|safe }}
          </section>
        </div>
        <div class="card-footer">
          <div class="row">
            <div class="col-12 text-start">
              {% if history.history_change_reason != None and history.history_change_reason|length > 0 %}
                  Motivo de cambio: {{ history.history_change_reason }}
              {% endif %}
            </div>
          </div>
        </div>
      </div>

    </div>
  
  </div>
</section>
{% endblock content %}